import type { Metadata } from "next";
import { Roboto_Condensed } from 'next/font/google'
import { DM_Serif_Text } from 'next/font/google'
import "./globals.css";
import Link from "next/link";
import { Facebook, Instagram, Twitter } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoCondensed = Roboto_Condensed({ subsets: ['latin'] })

const dMSerifText = DM_Serif_Text({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.className}`}
      >
        <div className="bg-white text-gray-900 ">
          <header className="bg-white shadow-md fixed top-0 left-0 w-full z-50">
            <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
              {/* Logo */}
              <Link href="/">
                <span className={`${dMSerifText.className} text-2xl font-bold text-yellow-500`}>Cameroun Tourisme</span>
              </Link>

              {/* Menu de navigation */}
              <nav className="hidden md:flex space-x-8">
                <Link href="/">
                  <span className="text-lg text-gray-700 hover:text-yellow-500">Accueil</span>
                </Link>
                <Link href="/destinations">
                  <span className="text-lg text-gray-700 hover:text-yellow-500">Destinations</span>
                </Link>
                <Link href="/culture">
                  <span className="text-lg text-gray-700 hover:text-yellow-500">Culture & Nature</span>
                </Link>
                <Link href="/blog">
                  <span className="text-lg text-gray-700 hover:text-yellow-500">Blog</span>
                </Link>
                <Link href="/planifier">
                  <span className="text-lg text-gray-700 hover:text-yellow-500">Planifier</span>
                </Link>
                <div className="relative">
                  <button className="text-lg text-gray-700 hover:text-yellow-500">
                    Langues
                  </button>
                  <div className="hidden absolute right-0 mt-2 w-32 bg-white shadow-lg rounded-md">
                    <Link href="/fr">
                      <span className="block px-4 py-2 text-gray-700 hover:bg-gray-100">Français</span>
                    </Link>
                    <Link href="/en">
                      <span className="block px-4 py-2 text-gray-700 hover:bg-gray-100">English</span>
                    </Link>
                  </div>
                </div>
              </nav>

              {/* Menu mobile */}
              <div className="md:hidden">
                <button className="text-2xl text-gray-700 hover:text-yellow-500" aria-label="Menu">
                  <i className="fas fa-bars"></i> {/* Ici tu peux utiliser une icône hamburger */}
                </button>
              </div>
            </div>
          </header>
          {children}

          <footer className="bg-gray-800 text-white py-8">
            <div className="max-w-7xl mx-auto px-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
                {/* Section 1: Liens importants */}
                <div>
                  <h3 className="text-xl font-semibold mb-4">Liens utiles</h3>
                  <ul className="space-y-2">
                    <li>
                      <Link href="/">
                        <span className="hover:text-yellow-500">Accueil</span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/destinations">
                        <span className="hover:text-yellow-500">Destinations</span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/culture">
                        <span className="hover:text-yellow-500">Culture & Nature</span>
                      </Link>
                    </li>
                    <li>
                      <Link href="/blog">
                        <span className="hover:text-yellow-500">Blog</span>
                      </Link>
                    </li>
                  </ul>
                </div>

                {/* Section 2: Contact */}
                <div>
                  <h3 className="text-xl font-semibold mb-4">Contact</h3>
                  <ul className="space-y-2">
                    <li>Email : <Link href="mailto:contact@camerountourisme.com" className="hover:text-yellow-500">contact@camerountourisme.com</Link></li>
                    <li>Téléphone : <Link href="tel:+237123456789" className="hover:text-yellow-500">+237 12 34 56 78 9</Link></li>
                    <li>Adresse : Yaoundé, Cameroun</li>
                  </ul>
                  <h3 className="text-xl font-semibold mt-4 mb-4">Suivez-nous</h3>
                  <div className="flex space-x-4">
                    <Link href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="text-yellow-500 hover:text-white transition-colors">
                      <Facebook className="w-6 h-6" />
                    </Link>
                    <Link href="https://twitter.com" target="_blank" rel="noopener noreferrer" className="text-yellow-500 hover:text-white transition-colors">
                      <Twitter className="w-6 h-6" />
                    </Link>
                    <Link href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="text-yellow-500 hover:text-white transition-colors">
                      <Instagram className="w-6 h-6" />
                    </Link>
                  </div>
                </div>


                {/* Section 4: Newsletter */}
                <div>
                  <h3 className="text-xl font-semibold mb-4">Abonnez-vous à notre newsletter</h3>
                  <p className="text-sm mb-4">Recevez les dernières nouvelles et offres exclusives sur les destinations camerounaises.</p>
                  <form className="flex flex-col lg:flex-row items-center space-y-2 lg:space-y-0 lg:space-x-2">
                    <input
                      type="email"
                      placeholder="Votre email"
                      className="p-2 rounded-md w-full sm:w-auto text-gray-700"
                      required
                    />
                    <button type="submit" className="bg-yellow-500 text-white px-6 py-2 rounded-md hover:bg-yellow-400">
                      {"S'abonner"}
                    </button>
                  </form>
                </div>
              </div>

              {/* Copyright */}
              <div className="mt-8 text-center text-sm text-gray-400">
                <p>© 2025 Cameroun Tourisme. Tous droits réservés.</p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
